### ISSUE TITLE
Way to be notified that server has closed websocket

### ISSUE THREAD

**Issue by sergigp** [andyglow/websocket-scala-client#9]
Hi,

We are using this library  in order to test at acceptance level our websocket application. 

We've tests like "if your are connected to the app through the websocket and don't send anything in 5 seconds, server will close the communication".

Is there a way to be notified through the `WebsocketClient` when server close the websocket or communication is broken?

Regards,
Sergi

**Comment by andyglow** [comment]
Hello!

Have you tried `WebsocketHandler.onFailure`?

**Comment by sergigp** [comment]
It looks fine in the code and seems what I need. Unfortunately the method `onFailure` is not in last version tagged of the websocket client (0.2.2).

Do you plan to release this soon?

Lots of thanks for your work, impressive project 💃

**Comment by andyglow** [comment]
Well, I've spent some time recently trying to reproduce this situation and discovered that `onFailure` didn't help. So I had to add test-server which is able to drop connection if client asks and extended examples to show how it is possible to handle exceptions `onFailure` and feature like `onClose` using builder semantic. Hope it will help. And yes I am going to release it today.

**Comment by andyglow** [comment]
I've just published `v0.2.3`. Please take a look. All the best!

**Comment by sergigp** [comment]
Lots of thanks Andy! 

![oletushuevos](https://cloud.githubusercontent.com/assets/764056/26412449/19eb3304-40a9-11e7-9db0-fc49aa142452.gif)

I will wait until version is published in maven repository, test it and let you know if it works fine.

Thanks for your effort!
Regards from Letgo Chat team!

**Comment by sergigp** [comment]
I've downloaded it thourgh bintray and it works like charm!

Thank you!

**Comment by andyglow** [comment]
Good! All the best!
чт, 25 мая 2017 г. в 16:16, Sergi GP <notifications@github.com>:
